import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainApp from '../component/mainapp'
 
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AI Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainApp />
    </div>
  )
}

export default Home
